from pathlib import Path
import json,html,os
root=Path(__file__).resolve().parents[1]; base=os.environ.get('SITE_URL','https://www.nickkorom.com').rstrip('/'); company='https://www.bnbaccelerator.com'; apply=company+'/apply/'
nav=[('Home','/'),('About','/about/'),('BNB Accelerator','/bnb-accelerator/'),('Speaker','/speaker/'),('Press','/press-media/')]
def button(label,url=apply,cls=''):return f'<a class="btn {cls}" href="{url}">{label} <span aria-hidden="true">↗</span></a>'
def cards(items):return '<div class="grid">'+''.join(f'<article class="card"><span class="num">0{i+1}</span><h3>{t}</h3><p>{p}</p>{f"<a class=text-link href={u}>Explore →</a>" if u else ""}</article>' for i,(t,p,u) in enumerate(items))+'</div>'
def section(content,cls=''):return f'<section class="section {cls}"><div class="wrap">{content}</div></section>'
def heading(label,title,desc=''):return f'<div class="section-title"><div><span class="eyebrow">{label}</span><h2>{title}</h2></div><p>{desc}</p></div>'
def pagehero(label,title,desc):return f'<section class="page-hero"><div class="wrap"><span class="eyebrow">{label}</span><h1>{title}</h1><p>{desc}</p></div></section>'
def cta():return '<section class="cta dark"><div class="wrap"><div><span class="eyebrow">Your next chapter</span><h2>Start with a better<br>property buying plan.</h2></div>'+button('Discuss your first STR',cls='light')+'</div></section>'
process=[('Define the right purchase','Start with your available capital, goals, timeline, and responsibilities. A clear buy box comes before a property search.',company+'/how-it-works/'),('Evaluate the actual deal','Review the market, property, financing, operating costs, and downside assumptions before making a purchase decision.',company+'/case-studies/'),('Coordinate the launch','Bring due diligence, furnishing, photography, listing setup, and the operating handoff together around a defined plan.',company+'/how-it-works/')]
home='''<section class="hero"><img src="/assets/nick-speaking.jpg" width="1920" height="1080" alt="Nicholas Korom speaking about entrepreneurship and real estate" fetchpriority="high"><div class="wrap"><div class="hero-copy"><span class="eyebrow">Entrepreneur. Investor. Founder.</span><h1>A clear path from<br>ambition to<br>property ownership.</h1><p>I’m Nicholas Korom. Through BNB Accelerator, I help investors navigate the work of buying and launching a short-term rental.</p><div class="actions">'''+button('Explore BNB Accelerator', '/bnb-accelerator/','light')+'''<a class="text-link" href="/about/">Meet Nicholas →</a></div><p class="name">NICHOLAS KOROM · FOUNDER OF BNB ACCELERATOR</p></div></div></section><div class="proof-bar"><div class="wrap"><span class="eyebrow label">BNB Accelerator company figures</span><div><strong>500+</strong><br><small>Properties closed</small></div><div><strong>80%</strong><br><small>Repeat buyer rate</small></div><a class="text-link" href="https://www.bnbaccelerator.com/case-studies/">Review client examples ↗</a></div></div>'''
home+=section(heading('A practical approach','Big goals. Thoughtful acquisitions.','Property ownership starts with a process you can understand and decisions you can stand behind.')+cards(process)+'<p class="small-note" style="margin-top:24px">Company figures are published by BNB Accelerator. Individual results vary; review property-specific examples and their assumptions.</p>')
home+=section('''<div class="split"><img class="portrait" src="/assets/nick-portrait.jpeg" width="768" height="960" loading="lazy" alt="Portrait of Nicholas Korom"><div><span class="eyebrow">Meet Nicholas</span><h2>An entrepreneur’s mindset.<br>An investor’s perspective.</h2><p>My path into real estate began with owning properties myself. Building BNB Accelerator brought those lessons into a coordinated acquisition and launch process for other investors.</p><p>My focus is straightforward: make the process clear, put the property at the center of the conversation, and help clients ask better questions before they buy.</p>'''+button('Read my story','/about/')+'''</div></div>''','alt')
home+=section(heading('The company behind the process','Meet BNB Accelerator.','A team that coordinates property sourcing, purchase support, and launch execution.')+cards([('Understand the service','See what the team coordinates and what remains your decision.',company+'/how-it-works/'),('Review the evidence','Explore client examples with property context and labeled financial figures.',company+'/case-studies/'),('Plan your first STR','Work through the purchase budget, property shortlist, and operating plan.',company+'/buy-short-term-rental/')]),'dark')
home+=section(heading('Beyond the acquisition','Ideas worth talking about.')+cards([('Speaking & podcasts','Conversations about entrepreneurship, business exits, and the realities of short-term rental ownership.','/speaker/'),('Press & media','Published coverage, a short biography, and resources for journalists and event organizers.','/press-media/'),('Connect with Nicholas','Choose the right path for investment questions, media requests, or speaking inquiries.','/contact/')]))
faqs=[('Is this Nick’s personal website or BNB Accelerator’s website?','This is Nicholas Korom’s personal website. BNB Accelerator’s website contains the company service details, client examples, and application process.'),('What does BNB Accelerator help with?','The company coordinates short-term rental sourcing, purchase support, and launch execution. You provide the capital, review the analysis, and approve material decisions.'),('Where should I start if I’m considering buying an STR?','Review the company process and client examples, then discuss your available capital, goals, timing, and operating expectations with the team.'),('Can I book Nicholas for an event or podcast?','Yes. Visit the Speaker page for topic ideas and the booking inquiry path.')]
home+=section(heading('Good questions come first','Before you take the next step.')+'<div class="faq">'+''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in faqs)+'</div>','alt')+cta()
about=pagehero('About Nicholas Korom','Built through experience.<br>Focused on execution.','Entrepreneur, real estate investor, and founder of BNB Accelerator.')+section('''<div class="split"><img class="portrait" src="/assets/nick-portrait.jpeg" width="768" height="960" alt="Nicholas Korom" fetchpriority="high"><div><span class="eyebrow">My story</span><h2>From building a business to building an acquisition process.</h2><p>I began investing in real estate in 2019. After building and exiting Patient Rhino in 2022, I focused on short-term rentals and the work that goes into selecting, buying, and preparing a property for guests.</p><p>BNB Accelerator grew from that experience. The team brings sourcing, transaction coordination, and launch support into a connected process, with the client approving the property and the important decisions along the way.</p><p>For me, the strongest conversations start with the details: the property, the assumptions, the responsibilities, and the plan after closing.</p>'''+button('See the company process',company+'/how-it-works/')+'''</div></div>''')+section(heading('Operating principles','The work behind a good decision.')+cards([('Make assumptions visible','Revenue, financing, operating costs, and reserves should be clear enough to question.',''),('Keep ownership personal','Each investor has different capital, goals, and responsibilities. The purchase needs to fit those facts.',''),('Plan beyond closing','Guest experience, furnishing, local operations, and the launch handoff belong in the acquisition conversation.','')]),'alt')+cta()
bnb=pagehero('Founded by Nicholas Korom','Your property.<br>A coordinated path to ownership.','BNB Accelerator supports investors through short-term rental sourcing, purchase coordination, and launch preparation.')+section(heading('How it works','From a defined search to a guest-ready property.')+cards(process))+section('''<div class="split"><div><span class="eyebrow">Built around your decisions</span><h2>Know the scope.<br>Know the responsibilities.</h2></div><div><p>The team coordinates the work. You supply the capital, review the analysis, approve the purchase, and choose your operating arrangement.</p><p>Financing, tax, legal, and ongoing property management decisions involve your chosen independent professionals. Review the company’s service scope before applying.</p>'''+button('Read the full process',company+'/how-it-works/')+'''</div></div>''','alt')+section(heading('Do your research','Review the evidence before the call.')+cards([('Client case studies','Look at the property context, acquisition details, and financial assumptions behind each example.',company+'/case-studies/'),('Selected properties','Explore the company’s selected deals, then follow through to deeper case-study material.',company+'/deals/'),('First-time buyer resources','Use the company’s worksheets to organize your budget, search, and launch plan.',company+'/buy-short-term-rental/')]))+cta()
speaker=pagehero('Speaking & podcasts','Practical conversations.<br>Real operating experience.','Book Nicholas Korom for conversations about entrepreneurship, business exits, and short-term rental acquisitions.')+section(heading('Topics for your audience','From business building to property ownership.')+cards([('The entrepreneur’s next chapter','Lessons from building and exiting a business, then bringing an operating mindset to real estate.',''),('Inside an STR acquisition','The questions, assumptions, and responsibilities that come between finding a listing and buying a property.',''),('Building a coordinated team','How sourcing, transactions, project work, and local operations connect around the investor.','')]))+section('''<div class="split"><div><span class="eyebrow">Booking inquiry</span><h2>Tell me about<br>your audience.</h2></div><div><p>Include the event or podcast name, audience, proposed topic, date, format, location, and your contact information in your inquiry.</p>'''+button('Request a speaking booking','https://www.nickkorom.com/contact/')+'''<p class="small-note" style="margin-top:20px">Booking requests currently use Nicholas’s existing contact form.</p></div></div>''','alt')
media=pagehero('Press & media','Nicholas Korom.<br>The story behind the work.','Published coverage and useful background for journalists, podcast hosts, and event organizers.')+section('''<span class="eyebrow">Published coverage</span><a class="resource" href="https://tycoonjournal.com/how-nicholas-korom-built-my-bnb-accelerator-around-the-part-of-real-estate-investing-nobody-wants-to-do/"><span class="tag">TYCOON JOURNAL</span><h3>Building BNB Accelerator around the work of real estate investing</h3><p>Read the published feature ↗</p></a><a class="resource" href="https://usavantage.com/how-nicholas-korom-turned-a-business-exit-into-my-bnb-accelerator/"><span class="tag">USA VANTAGE</span><h3>From a business exit to My BnB Accelerator</h3><p>Read the published feature ↗</p></a><a class="text-link" href="https://www.bnbaccelerator.com/#press">Explore more company coverage ↗</a>''')+section('''<div class="split"><div><span class="eyebrow">Short biography</span><h2>Background for<br>your next story.</h2></div><div><p>Nicholas Korom is an entrepreneur, real estate investor, and founder of BNB Accelerator. His work focuses on coordinating the sourcing, acquisition, and launch of short-term rental properties. He began investing in real estate in 2019 and exited Patient Rhino in 2022 before focusing on the short-term rental acquisition process.</p><a class="text-link" href="/assets/nick-portrait.jpeg" download="nicholas-korom-portrait.jpeg">Download Nicholas’s portrait ↓</a><br>'''+button('Send a media inquiry','https://www.nickkorom.com/contact/')+'''</div></div>''','alt')
contact=pagehero('Get in touch','Let’s start the<br>right conversation.','Investment questions, speaking invitations, and media inquiries have different starting points.')+section(cards([('Buy a short-term rental','Discuss your goals, available capital, timing, and acquisition plan directly with the BNB Accelerator team.',apply),('Speaking & podcasts','Share your audience, topic, date, and event format when requesting a booking.','https://www.nickkorom.com/contact/'),('Media & general inquiries','Use Nicholas’s existing contact form for interviews and other professional inquiries.','https://www.nickkorom.com/contact/')])+'<p class="small-note" style="margin-top:25px">Media and speaking inquiries are handled through Nicholas’s official contact form.</p>')
privacy=pagehero('Privacy','A simple, transparent<br>approach to privacy.','How this personal website handles visits and links to other services.')+section('''<div class="legal"><h2>Website visits</h2><p>This site does not include an advertising tracker or a native contact form. Its hosting provider, Vercel, may process standard request information to deliver and secure the website.</p><h2>Fonts and external services</h2><p>Google Fonts provides the website typography. Following links to BNB Accelerator, social platforms, press outlets, or the existing contact form takes you to another service with its own privacy policy.</p><h2>Inquiries</h2><p>Information submitted through an external form is handled by that form’s operator. Review its privacy information before submitting personal information.</p><h2>Privacy questions</h2><p>Contact Nicholas through the <a href="https://www.nickkorom.com/contact/">existing contact page</a> with questions about this website.</p></div>''')
pages=[('', 'Nicholas Korom | Founder of BNB Accelerator','Meet Nicholas Korom, entrepreneur, real estate investor and founder of BNB Accelerator. Explore his approach, speaking topics, and short-term rental acquisition resources.',home),('about','About Nicholas Korom | Entrepreneur & BNB Accelerator Founder','Discover Nicholas Korom’s entrepreneurial background, real estate experience, and operating principles behind BNB Accelerator.',about),('bnb-accelerator','BNB Accelerator | Nicholas Korom’s STR Acquisition Company','Explore BNB Accelerator’s short-term rental sourcing, purchase coordination, launch support, and client examples.',bnb),('speaker','Book Nicholas Korom | Speaking & Podcast Inquiries','Invite Nicholas Korom to discuss entrepreneurship, business exits, and the practical work of short-term rental acquisitions.',speaker),('press-media','Nicholas Korom Press & Media | Biography and Coverage','Find published Nicholas Korom coverage, a short biography, a downloadable portrait, and the media inquiry path.',media),('contact','Contact Nicholas Korom | BNB Accelerator, Speaking & Media','Connect with Nicholas Korom for speaking and media, or discuss your short-term rental acquisition with BNB Accelerator.',contact),('privacy-policy','Privacy | Nicholas Korom','Privacy information for Nicholas Korom’s personal website, hosting, typography, and external inquiry services.',privacy)]
def navigation(path):return ''.join(f'<a href="{u}" '+('aria-current="page"' if u==path else '')+f'>{t}</a>' for t,u in nav)
for slug,title,desc,content in pages:
 path='/'+(slug+'/' if slug else ''); url=base+path
 schema={'@context':'https://schema.org','@graph':[{'@type':'Person','@id':base+'/#nicholas-korom','name':'Nicholas Korom','alternateName':'Nick Korom','url':base+'/','image':base+'/assets/nick-portrait.jpeg','jobTitle':'Founder','worksFor':{'@type':'Organization','name':'BNB Accelerator','url':company},'sameAs':['https://www.linkedin.com/in/nickkorom/','https://www.instagram.com/nicholaskorom/','https://x.com/NicholasKorom']},{'@type':'WebSite','@id':base+'/#website','name':'Nicholas Korom','url':base+'/'},{'@type':'WebPage','name':title,'description':desc,'url':url,'isPartOf':{'@id':base+'/#website'},'about':{'@id':base+'/#nicholas-korom'}}]}
 header=f'<a class="skip" href="#main">Skip to content</a><header><div class="wrap"><a class="brand" href="/">Nicholas Korom<span>.</span></a><nav aria-label="Main navigation">{navigation(path)}</nav>{button("Let’s talk","/contact/")}<details class="mobile-menu"><summary>Menu ☰</summary><nav aria-label="Mobile navigation">{navigation(path)}<a href="/contact/">Contact</a></nav></details></div></header>'
 footer='''<footer><div class="wrap"><div class="footer-top"><div><a class="brand" href="/">Nicholas Korom<span>.</span></a><p>Entrepreneur. Real estate investor.<br>Founder of BNB Accelerator.</p></div><div class="footer-links"><div><strong>Explore</strong><a href="/about/">About Nicholas</a><a href="/speaker/">Speaking</a><a href="/press-media/">Press & media</a><a href="/contact/">Contact</a></div><div><strong>BNB Accelerator</strong><a href="https://www.bnbaccelerator.com/how-it-works/">The process ↗</a><a href="https://www.bnbaccelerator.com/case-studies/">Client examples ↗</a><a href="https://www.bnbaccelerator.com/apply/">Discuss your first STR ↗</a></div><div><strong>Follow Nicholas</strong><a href="https://www.linkedin.com/in/nickkorom/">LinkedIn ↗</a><a href="https://www.instagram.com/nicholaskorom/">Instagram ↗</a><a href="https://x.com/NicholasKorom">X ↗</a><a href="https://www.youtube.com/@mybnbaccelerator">YouTube ↗</a></div></div></div><div class="footer-bottom"><span>© 2026 Nicholas Korom. <a href="/privacy-policy/">Privacy</a></span><span>Real estate outcomes vary. Review company service details and use independent advisers for your tax, legal, and financing decisions.</span></div></div></footer>'''
 doc=f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)}</title><meta name="description" content="{html.escape(desc,quote=True)}"><link rel="canonical" href="{url}"><meta property="og:type" content="website"><meta property="og:title" content="{html.escape(title,quote=True)}"><meta property="og:description" content="{html.escape(desc,quote=True)}"><meta property="og:url" content="{url}"><meta property="og:image" content="{base}/assets/nick-speaking.jpg"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#172724"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="/assets/site.css"><script type="application/ld+json">{json.dumps(schema)}</script></head><body>{header}<main id="main">{content}</main>{footer}</body></html>'
 out=root/(slug+'/index.html' if slug else 'index.html');out.parent.mkdir(exist_ok=True,parents=True);out.write_text(doc)
(root/'assets/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#172724"/><text x="32" y="43" text-anchor="middle" fill="#f7f6f1" font-size="30" font-family="sans-serif">NK</text></svg>')
(root/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+base+'/sitemap.xml\n')
(root/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+base+'/'+(s+'/' if s else '')+'</loc></url>' for s,*_ in pages)+'</urlset>')
(root/'llms.txt').write_text('# Nicholas Korom\n\nPersonal website of Nicholas Korom, founder of BNB Accelerator.\n\n'+''.join(f'- [{t}]({base}/{s+"/" if s else ""}): {d}\n' for s,t,d,_ in pages))
(root/'vercel.json').write_text(json.dumps({'cleanUrls':True,'trailingSlash':True,'headers':[{'source':'/assets/(.*)','headers':[{'key':'Cache-Control','value':'public, max-age=3600, stale-while-revalidate=86400'}]},{'source':'/(.*)','headers':[{'key':'X-Content-Type-Options','value':'nosniff'},{'key':'Referrer-Policy','value':'strict-origin-when-cross-origin'}]}]},indent=2))
print('Built',len(pages),'pages')
